### ISSUE TITLE
Search history in vi editing mode

### ISSUE THREAD

**Issue by aRkadeFR** [milkbikis/powerline-shell#113]
Hi, 

I'm using the vi editing mode of the shell, and the powerline-shell doesn't display right when I do a search in the history with the '/' character (normal mode).

**Comment by nickgronow** [comment]
I am having this exact same issue.  Are there any other powerline shell users that use vi mode?

**Comment by b-ryan** [comment]
Hey @aRkadeFR and @nickgronow. Sorry this never got looked at sooner. I use vi mode and just tried this out -- didn't have any issues. Let me know if you still do.
