### ISSUE TITLE
Minimize whitespace

### ISSUE THREAD

**Issue by mbrevda** [milkbikis/powerline-shell#116]
It would be nice to be able to minimize the amount of whitespace that is displayed (such as between directory names). Also, is there any way to redefine the separator for specific segments in the config file? I would prefer to have the traditional ```/``` as a directory separator.

This is what I want to accomplish: http://imgur.com/NXoUmm2

**Comment by faxm0dem** [comment]
:+1:

**Comment by b-ryan** [comment]
Just going to close this as dead. The project has changed a lot. If anyone decides to go at a new segment feel free. Although nowadays there is the `--cwd-mode` which allows a more compact view. I use `--cwd-mode plain` myself.
