### ISSUE TITLE
Breaks With System Python 3 or Inside of a Python 3 Virtualenv

### ISSUE THREAD

**Issue by wbond** [milkbikis/powerline-shell#118]
Since the code is not py2 and py3 compatible, it breaks if you enter a Python 3 virtualenv (such as on OS X). As in #100, it will also break if your system has `python` set to py3, such as on Arch linux.

The options seem to be:

1. Provide instructions to make a `python2` symlink on the users machine and update `powerline-shell.py` to `#!/usr/bin/env python2`
2. Hard code the python path into `powerline-shell.py` when running `./install.py`
3. Update the code to work with py2 and py3. It seems #66 was an attempt at that. If you are interested in this approach, I'd be happy to send a pull request against the current state of master.

**Comment by noteventhrice** [comment]
this is one dank issue tbh +1

**Comment by fizyk** [comment]
Any plans for supporting python 3 out of the box? It's been biting me for a while as it hinders virtualenv with python 3 activation.

And as for how to maintain compatibility, tests with running them on travis-ci would be definitely helpful.
