### ISSUE TITLE
number of jobs does not work

### ISSUE THREAD

**Issue by mbauhardt** [milkbikis/powerline-shell#134]
Hi,
i tried to use to see the number of jobs which is running in background. But no value is shown.

e.g.

    sleep 10
    ^z
    bg

I guess the segment for jobs should be show the number 1 for 10 seconds. But there is no value.

Marko

**Comment by b-ryan** [comment]
I just tried both things and the number of jobs was shown successfully. This is an old issue so it could have been fixed over the course of the past year or so.
