### ISSUE TITLE
"_update_ps1: command not found" when launching an inner shell

### ISSUE THREAD

**Issue by LeonardoGentile** [milkbikis/powerline-shell#144]
I'm not sure if this is an issue but if by mistake I launch an _inner_ shell like so `sh` (bash) all the prompt that follows will not work properly and I will get back the following error for each line prompt
``` 
_update_ps1: command not found
```

**Comment by b-ryan** [comment]
I wasn't able to reproduce this. If you are still having this issue could you maybe provide a screen shot? Since this issue is really old I'd like to close, but feel free to open if need be.

**Comment by jay-to-the-dee** [comment]
Just git pulled and re-run install.py and this still happens! I'll try and get a screenshot but you should be able to reproduce by typing 'su anyothernormaluserhere' in a normal shell.

**Comment by jay-to-the-dee** [comment]
![powershellbug](https://cloud.githubusercontent.com/assets/5121114/11405092/a3ce46f2-939d-11e5-90f6-d9b99efc68e9.png)

**Comment by b-ryan** [comment]
@jay-to-the-dee are you `export`ing `_update_ps1` in your bashrc? The README used to say to do

```
export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
```

But we have since changed this to recommend doing just:

```
PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
```

See https://github.com/milkbikis/powerline-shell#bash. I think this will fix your issue.

**Comment by jay-to-the-dee** [comment]
Boom! And that indeed fixes the bug! Thanks a lot! :)

**Comment by b-ryan** [comment]
Great! no problem

**Comment by kanggara75** [comment]
Thanks a lot....
that fixes  my problem
