### ISSUE TITLE
Repeating path if max_depth <=2

### ISSUE THREAD

**Issue by LeonardoGentile** [milkbikis/powerline-shell#148]
Calling powerline-shell with
```
--cwd-max-depth 2
```
or `1` cause it to render some part of the path twice. 
For example if I `cd /Library/Python/2.7` this is the result:
![image](https://cloud.githubusercontent.com/assets/412061/3397238/b33ddd2e-fd1b-11e3-93c3-2f21024e979c.png)

**Comment by b-ryan** [comment]
https://github.com/milkbikis/powerline-shell/pull/209

Thanks @LeonardoGentile and @welbornprod. Sorry it took so long to get fixed.
