### ISSUE TITLE
Red Background with "push simple" in global .gitconfig 

### ISSUE THREAD

**Issue by LeonardoGentile** [milkbikis/powerline-shell#149]
Adding this configuration on my global .gitconfig
```
 [push]
    default = simple
```
will always show a red background on the git segment even if the working directory is clean

**Comment by b-ryan** [comment]
@LeonardoGentile I can't reproduce this. It would be great if you could provide a demo of the behavior, ie. a screen capture of you doing the following:

```
git config --global --unset push.default
cd [some-git-repo]
# should show green
git config --global push.default simple
# should show red
```

**Comment by LeonardoGentile** [comment]
@b-ryan it's not happening anymore
Since then I installed the script several times so maybe something was fixed along the way or I've changed something in my `.bash_profile` that fixed it. :+1:

**Comment by b-ryan** [comment]
Ok great
