### ISSUE TITLE
color customization

### ISSUE THREAD

**Issue by badeip** [milkbikis/powerline-shell#16]
Nice work.

I am not too found of a having a pink git branch indicator though.
Can you add the possibility of themes/easy customization of colors.

Thanks,

Btw: I find that the following colors works ok for me:

diff --git powerline-bash.py powerline-bash.py
index 78bc030..c0e3fd4 100755
--- powerline-bash.py
+++ powerline-bash.py
@@ -111,8 +111,8 @@ def get_git_status():
     return has_pending_commits, has_untracked_files, origin_position
 
 def add_git_segment(powerline, cwd):
-    green = 148
-    red = 161
+    green = 0
+    red = 136
     #cmd = "git branch 2> /dev/null | grep -e '\\*'"
     p1 = subprocess.Popen(['git', 'branch'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
     p2 = subprocess.Popen(['grep', '-e', '\\*'], stdin=p1.stdout, stdout=subprocess.PIPE)
@@ -124,8 +124,8 @@ def add_git_segment(powerline, cwd):
     branch += origin_position
     if has_untracked_files:
         branch += ' +'
-    bg = green
-    fg = 0
+    bg = 2
+    fg = 15
     if has_pending_commits:
         bg = red
         fg = 15
@@ -189,7 +189,7 @@ def add_root_indicator(powerline, error):
     fg = 15
     if int(error) != 0:
         fg = 15
-        bg = 161
+        bg = 52
     powerline.append(Segment(' \\$ ', fg, bg))
 
 if __name__ == '__main__':

**Comment by b-ryan** [comment]
This was taken care of a long time ago. See the README docs here: https://github.com/milkbikis/powerline-shell#themes
