### ISSUE TITLE
Had trouble with `su` command

### ISSUE THREAD

**Issue by Endle** [milkbikis/powerline-shell#161]
I added
```
function _update_ps1() {
   export PS1="$(~/src/powerline-shell/powerline-shell.py \
   --mode compatible --cwd-max-depth 6
   $? 2> /dev/null)"
}

export PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
```
in my `.bashrc`. However, after I typing `su`, bash complained
`_update_ps1: command not found`

Is this a bug? How can I get rid of it?
Thank you.

**Comment by b-ryan** [comment]
@Endle the current instructions in the README have removed the recommendation to `export PROMPT_COMMAND`. If you do not `export` this variable then subshells will not be affected. Let me know if you still run into any issues.
