### ISSUE TITLE
Alternative project: https://github.com/nimiq/promptastic

### ISSUE THREAD

**Issue by nimiq** [milkbikis/powerline-shell#167]
I have been using *powerline-shell* for a while and, as we all see, it is a great project but unfortunately the development is kind of stuck and the software is a bit buggy. So I started an alternative project, heavily inspired by powerline-shell, take a look:
https://github.com/nimiq/promptastic

**Comment by ryanoasis** [comment]
@nimiq I am thinking about switching over. Are there any big obvious differences in terms of features currently supported on powerline-shell vs your project (promptastic) ?

Thanks!

**Comment by nimiq** [comment]
Not much difference between *powerline-shell* and *promptastic* in terms of features. I believe *promptastic* has a better layout and the project itself is more actively maintained (so less buggy), but I am the author of *promptastic* so my point of view is biased of course. If you have used *powerline-shell* for a while and you are happy with that then do not switch over, in all other cases go for *promptastic*!

**Comment by ryanoasis** [comment]
Thanks. Yeah I am mostly happy with it except it is no longer maintained. I still plan to check out your project and maybe switch over :smile:

**Comment by fgmacedo** [comment]
Well done @nimiq! Glad it works with Python 2 and 3 out of the box! Nice!

**Comment by bersace** [comment]
Is it possible to merge the projects ?

**Comment by b-ryan** [comment]
Hey @nimiq -- I have been trying to get this repo back into shape. Part of that process is closing out old issues. So while your project looks pretty nice, I don't think this issue need stay open.

**Comment by nimiq** [comment]
Alright, good luck!!

**Comment by bersace** [comment]
@b-ryan awesome !!!
