### ISSUE TITLE
powerline-shell.py: error: unrecognized arguments: 2

### ISSUE THREAD

**Issue by yzld2002** [milkbikis/powerline-shell#178]
I'm using bash and I followed the instruction in README. 
But I got this error report:
```
usage: powerline-shell.py [-h] [--cwd-only] [--cwd-max-depth CWD_MAX_DEPTH]
                          [--colorize-hostname]
                          [--mode {patched,compatible,flat}]
                          [--shell {bash,zsh,bare}]
                          [prev_error]
powerline-shell.py: error: unrecognized arguments: 2
```
My Python vision is 2.7.8. What's wrong with my operation? thx~

**Comment by itJunky** [comment]
wow, maybe you think, what all people telepathists? And we know what parameters you use at start or what qoute you not type in config?

cat .bashrc or gtfo

**Comment by milkbikis** [comment]
Can you paste your bashrc here?

**Comment by yzld2002** [comment]
Sorry, I input a spare space between 2 and >.  It's my mistake. I appologize to everyone for it...
