### ISSUE TITLE
Invite some collaborators?

### ISSUE THREAD

**Issue by ryanoasis** [milkbikis/powerline-shell#185]
There are many issues and PR's, maybe time to open up to some trusted individuals to help out more directly?

**Comment by ovr** [comment]
:+1:

**Comment by dserodio** [comment]
This repo seems abandoned (last commit on Nov 2, 2014), so I've been merging interesting PRs on my own fork.

**Comment by ryanoasis** [comment]
@dserodio Nice. Although it would be good to have an official one or main fork to contribute on :worried: 

@milkbikis do you plan to keep working on this repo or if not maybe transfering ownership?

It seems like a lot of us still use this project

**Comment by ryanoasis** [comment]
I have reached out to @milkbikis through e-mail in a hope to know if he has any future plans to maintain this project or if there is someway he would be willing to transfer it or at least promote a de facto fork where we can all contribute and get things closed and PRs merged in.

**Comment by caseyfw** [comment]
Hey @milkbikis could you invite some collaborators?

**Comment by b-ryan** [comment]
So I have been a collaborator on this for some time. I fell away from actually using the project and then when I returned, I saw there wasn't much activity. I tried emailing @milkbikis to see if he would be cool with me merging pull requests. I felt weird doing so since I hadn't kept up with the code / project.

Since there has been such stagnation in the project I will begin reviewing and merging PRs. Hopefully Shrey doesn't have issues with this.

**Comment by ryanoasis** [comment]
@b-ryan looks like you've been busy reviewing and merging PRs :+1:. Just wanted to say thanks!

**Comment by b-ryan** [comment]
@ryanoasis sure thing! I'll try to get this project back in shape.

**Comment by caseyfw** [comment]
Cheers @b-ryan !

**Comment by ryanoasis** [comment]
@b-ryan Maybe this can be closed? It seems like no collaborators will be added unfortunately.

Seems like in the short term your efforts have really gotten things turned around and I'm grateful :+1: 

My only worry about the project staying on this repo is that for whatever reason you (@b-ryan) get too busy, go inactive, sail off the edge of the earth, etc then we are all stuck again :cry:

**Comment by b-ryan** [comment]
@ryanoasis I have the same concerns. I don't want this project to die if I suddenly forget about it or whatever else happens. I have been thinking about this lately myself.

Some thoughts I have had are:

* Change the README to indicate the project has permanently moved to my own fork. Then I can invite more collaborators.
* Contact GitHub to ask if they would make me the owner.

Maybe there are other options? I am also wary of doing these things in case @milkbikis shows up again and feels like his project was stolen. So even if I pursue one of these options, I don't think I will do so for another few months.

**Comment by ryanoasis** [comment]
@b-ryan Sounds logical to me. Probably best to revisit this after some more time has passed :+1:

**Comment by b-ryan** [comment]
Alright, let's close this for now then.
