### ISSUE TITLE
Unicode character in place of the dollar sign causes strange behaviour

### ISSUE THREAD

**Issue by verandaguy** [milkbikis/powerline-shell#188]
I'm trying to update the dollar sign in the `root.py` segment to be a λ (Greek small letter lambda, U+033B). To do this, I performed the following substitution:

```
'bash': ' \\$ ',
'zsh': ' \\$ ',
'bare': ' $ ',
```
Changed to
```
# -*- coding: utf-8 -*-

...

'bash': ' λ ',
'zsh': ' λ ',
'bare': ' λ ',
```
Upon saving these changes and running `./install.sh` my shell disappeared (I've got a symlink to the python script, updates take effect immediately).

I also tried replacing `\\$` with `$LAMBDA`, which I bound to the unicode λ in my `.zshrc`. This likewise failed, showing a blank zero-width character in place of the dollar sign in the prompt.

Is there any way to get the shell to display a unicode replacement for the dollar sign?

**Comment by blieque** [comment]
You may change it to a lowercase lambda, but you must create a Unicode string. In Python 3 this is done automatically, but Python 2 requires an explicit prefix:

    'bash': u' \u03bb ',
    'zsh': u' \u03bb ',
    'bare': u' \u03bb '

The `coding` line at the beginning of the file is not required as far as I know.

**Comment by b-ryan** [comment]
@

**Comment by b-ryan** [comment]
@verandaguy, what @blieque said is accurate. If you follow the instructions there you will be able to use the lambda symbol.
