### ISSUE TITLE
strange caracters and no arrows

### ISSUE THREAD

**Issue by clicproxy** [milkbikis/powerline-shell#190]
Here's a screenshot : http://i.imgur.com/8pWYwzL.png

Why I do not have beautiful arrows ? 

Thanks for your support,
David

**Comment by verandaguy** [comment]
This usually happens when you aren't using a font patched to support Powerline. Generally speaking, the Unicode characters representing those arrows are in the so-called private-use Unicode space, so they aren't usually bundled with fonts by default — hence the patches.

See [here](https://github.com/powerline/fonts) for compatible fonts.

**Comment by clicproxy** [comment]
Hello,

I've installed theses fonts but no changes.

    $ ./install.sh 
    All Powerline fonts installed to /home/david/.fonts

But same result (after closing and after reboot).

![image](https://cloud.githubusercontent.com/assets/1042251/8285107/93fc64b4-1901-11e5-81fd-54475ccbbfbd.png)

**Comment by verandaguy** [comment]
You've installed them -- but have you configured your terminal to use them?

**Comment by clicproxy** [comment]
Houra ! 

I was thinking that the gnome-terminal select them automaticaly. 

![image](https://cloud.githubusercontent.com/assets/1042251/8285236/53243592-1902-11e5-9174-09668c71b82e.png)

**Comment by verandaguy** [comment]
:+1:

**Comment by stonier** [comment]
I have exactly the same screenshot. It's not entirely clear however, how you get your terminal to use them.

@clicproxy can you briefly mention or point to how you achieved this?

**Comment by ryanoasis** [comment]
@stonier I think it was probably in profile > profile preferences > general > font

**Comment by stonier** [comment]
Oh ho...with all the command line documentation creating so much noise over in the powerline docs, I didn't even think about the trivially obvious.

Works fine now - thanks :neckbeard:

**Comment by ryanoasis** [comment]
@stonier heh you're welcome :)
