### ISSUE TITLE
No prompt displayed when git branch name contains accentuated characters

### ISSUE THREAD

**Issue by AugierLe42e** [milkbikis/powerline-shell#191]
I made a mistake while creating a git branche with a french name. It contained a "è". After that, prompt refused to display though I was able to type commands.

**Comment by verandaguy** [comment]
Possibly related to #188?

**Comment by b-ryan** [comment]
Hi @AugierLe42e, I just tested this out without any problems. Can you update to the latest version of this project and if you still have any issues, please feel free to re-open this.
