### ISSUE TITLE
Unknown characters in prompt, no arrows

### ISSUE THREAD

**Issue by thibmaek** [milkbikis/powerline-shell#213]
<img width="842" alt="screen shot 2015-11-23 at 14 06 50" src="https://cloud.githubusercontent.com/assets/6213695/11337210/82313224-91eb-11e5-807a-544ba55623f8.png">

Dump of $PS1:
`\[\e[38;5;7m\]\[\e[48;5;8m\] ~ \[\e[48;5;8m\]\[\e[38;5;7m\]\[\e[38;5;7m\]\[\e[48;5;8m\] Documents \[\e[48;5;8m\]\[\e[38;5;7m\]\[\e[38;5;7m\]\[\e[48;5;8m\] Development \[\e[48;5;8m\]\[\e[38;5;7m\]\[\e[38;5;7m\]\[\e[48;5;8m\] powerline \[\e[48;5;1m\]\[\e[38;5;8m\]\[\e[38;5;15m\]\[\e[48;5;1m\] master \[\e[48;5;52m\]\[\e[38;5;1m\]\[\e[38;5;15m\]\[\e[48;5;52m\] ❓ \[\e[48;5;8m\]\[\e[38;5;52m\]\[\e[38;5;15m\]\[\e[48;5;8m\] \$ \[\e[0m\]\[\e[38;5;8m\]\[\e[0m\]`

**Comment by b-ryan** [comment]
@thibmaek have you followed the instructions on patching your font? See https://github.com/milkbikis/powerline-shell#setup

**Comment by thibmaek** [comment]
Damn, should've kept my mouth shut and checked that out first.

Thanks, works now.
