### ISSUE TITLE
Can't get it working on Arch

### ISSUE THREAD

**Issue by Arengorn** [milkbikis/powerline-shell#216]
I had set this up on Ubuntu with no problems whatsoever, however I've been unable to get this to work on my work PC that is currently running Arch Linux 64 bit. I have followed the install instructions precisely two time already but without success. I use the fish shell, and with powerline active all I can see is the following
![snapshot1](https://cloud.githubusercontent.com/assets/7243783/11487940/db39f2e8-97a9-11e5-87c2-ab3538c99fda.png)

**Comment by ceholden** [comment]
Hi @Arengorn 

I was able to reproduce what you're seeing in `fish` on Arch using the `--colorize-hostname` option. I couldn't reproduce any errors using other optional arguments to `powerline-shell.py`, so if you're not using `--colorize-hostname` it would help to know what segments you're using and what optional arguments you've passed to `powerline-shell.py` in your `fish_prompt`.

As Arch ships Python3 by default and Ubuntu is still on Python2, you're likely running into some Python 3 specific bugs in the code. To confirm, you could remove or comment out the `^/dev/null` in the your `fish_prompt` function to see the Python exceptions raised preventing your shell prompt from executing.

There are three Python 3 specific errors I've found in `lib/color_compliment.py` that I'll send a PR for. The first you are likely to see is `ImportError: No module named 'colortrans'`.

For now you could either,

1. Install `python2` and change the hashbang in `powerline-shell.py` to read `#!/usr/bin/env python2`
2. Temporarily switch to my branch containing fixes to the 3 bugs I mentioned earlier
    * https://github.com/ceholden/powerline-shell/tree/py3

Hope this helps

**Comment by b-ryan** [comment]
@Arengorn I just merged @ceholden's fix for python 3 support in `lib/color_compliment.py`. Can you check whether this is working for you after that change?

**Comment by Arengorn** [comment]
@ceholden Thanks a lot! @b-ryan I have no access to my work computer currently, so I'll only be able to test it on the fifth on January, I'll make sure to let you guys know if it worked, until then, happy new year!

**Comment by Arengorn** [comment]
Just tested this and it works perfectly, no issues whatsoever.
Thanks a bunch for the quick fix guys.
