### ISSUE TITLE
python2: No such file or directory

### ISSUE THREAD

**Issue by sajadabedi** [milkbikis/powerline-shell#217]
When i clone repo and run ./install.py show me error!
<img width="652" alt="screen shot 1394-09-24 at 6 40 49 am" src="https://cloud.githubusercontent.com/assets/5726597/11800994/d6247ef6-a2f6-11e5-955c-a8c1c3de0b15.png">

how can i fix this?

**Comment by b-ryan** [comment]
Hi @sajadabedi, I just made this change: https://github.com/milkbikis/powerline-shell/commit/b9845c56f3aa62cd2c6f42a914985f1bc3ff148d

This should solve the issue for you. Let me know if you run into anything else.
