### ISSUE TITLE
Error message in git repo's .git directory

### ISSUE THREAD

**Issue by yegle** [milkbikis/powerline-shell#48]
Suppose `~/git/myproject` is a git repo. If you change directory to `~/git/myproject/.git` and press enter, `powerline-bash` will try to run `git status --ignore-submodules`, which will generate an error message

    fatal: This operation must be run in a work tree

**Comment by b-ryan** [comment]
There is at this point in time no error message within a `.git` directory. The `git` segment doesn't show anything when you are in this directory. Maybe that should change, but it's debatable. Going to close this.
